# This file is part of the Admin DDD Extensions Bundle.
#
# Copyright (c) 2017-present LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Gorka Laucirica <gorka.lauzirika@gmail.com>

services:
    lin3s_admin_ddd_extension.action.type.handle_command:
        class: LIN3S\AdminDDDExtensionsBundle\Action\HandleCommandActionType
        arguments:
           - "@lin3s_admin.form.handler"
           - "@lin3s.cms_kernel.application.command_bus"
           - "@twig"
           - "@session.flash_bag"
           - "@router"
        tags:
            - { name: 'lin3s_admin.action', alias: ddd_handle_command }
